In [1]:
# advanced functions in pandas through the dataset 
# knowing abt the dataset-chapter1

In [2]:
import pandas as pd
data = pd.read_csv("file.csv")

In [3]:
data.columns

Index(['Unnamed: 0', 'customer_id', 'order_date', 'order_id', 'Discount',
       'Name', 'Price', 'Product_ID', 'Product_Category', 'Product_Color',
       'Quantity', 'Total_Computed', 'Total_Pre_Discount'],
      dtype='object')

In [4]:
#drop a column in dataframe
#here axis=0 represents index droping , axis =1 represents column dropping
data = data.drop(['Unnamed: 0'],axis=1)
len(data.columns)

12

In [5]:
#checking the info about the data
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32412 entries, 0 to 32411
Data columns (total 12 columns):
customer_id           32412 non-null object
order_date            32412 non-null object
order_id              32412 non-null object
Discount              32412 non-null float64
Name                  32412 non-null object
Price                 32408 non-null float64
Product_ID            32412 non-null object
Product_Category      32412 non-null object
Product_Color         32000 non-null object
Quantity              32412 non-null float64
Total_Computed        32412 non-null float64
Total_Pre_Discount    32412 non-null float64
dtypes: float64(5), object(7)
memory usage: 3.0+ MB

customer_id             0
order_date              0
order_id                0
Discount                0
Name                    0
Price                   4
Product_ID              0
Product_Category        0
Product_Color         412
Quantity                0
Total_Computed          0
Total_Pre_Discount      0
dtype: int64

In [6]:
# major operations in pandas
#print(data.Product_Color.unique())
# to print total number of observations in dataset
data.shape
data.head()
data['order_date'] = pd.to_datetime(data['order_date'])
data['year'] = pd.DatetimeIndex(data['order_date']).year
data['month'] = pd.DatetimeIndex(data['order_date']).month
#pd.DatetimeIndex is a subclass of metadata that carry metadata such as frequency of information

In [7]:
#indeexing of operations 
#loc[],iloc[],ix[],[]
#data.head()
#first== reterving only particular columns
data[['Name','Price','Product_Category']]
# second == selecting only single row = .loc(selects particular column based on the labels in rows in columns)
data.loc[0:9] #selects based on the index - it reterives 8 rows 
first = data.loc[[0,9], 
                   ["Name",'year']] 
second = data.loc[:, 
                   ["Name",'year']] # selects all the rows and specified columns
# third by position == iloc[6]-reterives sixth position rows
data.iloc[[7],[4]] # by indexinteger position [rows and columns]
data.iloc[[0,5],[0,7,6]]
data.iloc[[19],[7]]

#fourth by label and integer based ,however it is deprecated in recent versions of pandas, for example
data.ix[0]
data.iloc[[19],[7]] #19 th column product_name

C:\Users\Admin\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated

   Product_Category
19        Furniture

In [8]:
# summarizing operations 
data.describe()# summerizes only integer columns
data.describe(include="all")# it includes all the columns
data.Name.describe() # summerizes only one column 
# most and least occurences
data.Product_Category.value_counts().head()#lists number of times the product is used
data.Product_Category.value_counts().tail()# least occurences

Lighting            22211
Home Accessories     8269
Furniture            1891
Jewelry                32
Fashion                 9
Name: Product_Category, dtype: int64

In [9]:
# Filtering and sorting in pandas
# six ways to sort in pandas
# first === sorting values by column 
col_sort = data.sort_values('Product_Category')# sorts by product_category by first asc and last by desc
# second ===  sort df based on values of column by desc order
col_desc_sort = data.sort_values('Price',ascending= False)
#print(col_desc_sort)
# third === sort values and put missing values first in the df 
col_missing_value_first = data.sort_values('Price',na_position='first')
#print(col_missing_value_first)
# fourth === sort dataframe based on column in place,i.e without creating new dataframe 
col_inplace_sort = data.sort_values('Price',inplace = True,ascending = False)
#print(col_inplace_sort)
#fifth = sort df based on index 
index_sorting = data.sort_index(inplace=True)
#print(index_sorting)
# sort values by multiple columns
multiple_sort = data.sort_values(['Name','Price'])
multiple_sort

,customer_id,order_date,order_id,Discount,Name,Price,Product_ID,Product_Category,Product_Color,Quantity,Total_Computed,Total_Pre_Discount,year,month
8334,4032fde29e426e6b21d397dab70c00885967b1208b24c9...,2018-07-10,CS165348,0.0,- None -,2.0,"Harp, 8 inch Brass",Lighting,NaN,1.0,5.0,5.0,2018,7
21525,a946a5436ad6605dc423593ad481f0739114558944c52a...,2019-02-07,INV038724,0.0,1/2 Diameter Pipe Kit (Gold Leaf),30.0,PIPE101GL,Lighting,Gold,1.0,75.0,75.0,2019,2
12246,5e12fa5e030b75a6e256dd24a0b00dec17a4a59b4fd29f...,2017-09-14,INV017215,0.0,1/2 Diameter Pipe Kit (Natural Brass),30.0,PIPE001NB,Lighting,Brass,3.0,225.0,225.0,2017,9
24316,bfbc8333440173686670da83906e000d121bfade55c84c...,2019-02-25,INV039724,0.0,1/2 Diameter Pipe Kit (Natural Brass),30.0,PIPE001NB,Lighting,Brass,3.0,225.0,225.0,2019,2
24381,c05c49acdbd6fe6acbcb9d5e83f05b68fe0d3da3cafe37...,2020-01-28,CS193132,0.0,1/2 Diameter Pipe Kit (Natural Brass),30.0,PIPE001NB,Lighting,Brass,1.0,75.0,75.0,2020,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10440,501760870123b60dd880126105ca8b05bb0669e0055948...,2016-10-26,INV003484,0.0,Zinc Obelisk (Small),25.0,44-72-0232,Home Accessories,Zinc,1.0,62.5,62.5,2016,10
10083,4db9c94b946cb06bb374b200c66b39ea7aa3bcfb920eb3...,2016-10-17,INV002928,0.0,Zinc Obelisk Large,55.0,20-1096BLKZ,Home Accessories,Zinc,1.0,137.5,137.5,2016,10
10442,501760870123b60dd880126105ca8b05bb0669e0055948...,2016-10-26,INV003484,0.0,Zinc Obelisk Large,55.0,20-1096BLKZ,Home Accessories,Zinc,1.0,137.5,137.5,2016,10
29422,e83262c0b7ac1ba8cc35864a048014c1f065fb81d0096b...,2019-08-05,INV047741,0.0,Zodiac Ceramic Table Lamp (Blue),159.0,13-1309,Lighting,Blue,1.0,397.5,397.5,2019,8
30540,f11a4eeab3b6d874b6845e45a964de9250f5e2d442603c...,2019-06-06,CS181117,0.0,Zodiac Ceramic Table Lamp (Blue),159.0,13-1309,Lighting,Blue,2.0,795.0,795.0,2019,6

In [35]:
import numpy as np
# grouping operations
# works on split-apply-combiine method
#spliting the groups based on certain condition
# appling function to all the groups
# combaining into final data structure
#first == based on product category the average product range is taken 
data_split_grouping = data.groupby(['Product_Category']).Price.count()
# second == based on multiple columns grouping 
data_muliple_split_grouping = data.groupby(['Product_Category','Name']).Total_Computed.sum().reset_index()# reset_index resets the index to original position
data_muliple_split_grouping
# third == applying multiple functions at once  without using numpy and lambda method
data_apply_func = data.groupby(['Product_Category']).agg({'Price':['count','mean'], 
                         'Total_Computed':'sum'}).reset_index()
# fourth == using np  applying multiple functions 
data_apply_numpy = data.groupby(['Product_Category']).agg([np.sum, np.mean, np.std])
# fifth  == grouping through particular category
data_lighting_grouping = data[data['Product_Category'] == 'Lighting'].groupby('Product_Category').Price.mean()
data_lighting_grouping
# for reference https://github.com/guipsamora/pandas_exercises/blob/master/03_Grouping/Occupation/Exercises_with_solutions.ipynb

Series([], Name: Price, dtype: float64)

In [ ]:
# apply operations